version: 2

updates:
  - package-ecosystem: gomod
    directory: /apps/api-server
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Zurich
    groups:
      patch-updates:
        update-types: [patch]
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /apps/dashboard
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Zurich
    groups:
      patch-updates:
        update-types: [patch]
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      actions-updates:
        update-types: [minor, patch]
