version: "2"

run:
  go: "1.24"
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - revive
    - gocritic
    - modernize
    - misspell
    - unconvert
    - unparam
    - gosec
    - bodyclose
    - nilerr
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gocritic

formatters:
  enable:
    - gofmt
    - goimports
