import {
  LayoutDashboard,
  ShoppingCart,
  Truck,
  RotateCcw,
  FileText,
  Receipt,
  Package,
  Plug,
  Users,
  Building2,
  Bell,
  ListChecks,
  TextCursorInput,
  FolderTree,
  ScrollText,
  Webhook,
  Factory,
  Zap,
  Upload,
  Download,
  BarChart3,
  RefreshCw,
  Warehouse,
  Contact,
  Printer,
  ScanBarcode,
  BadgePercent,
  ClipboardList,
  ClipboardCheck,
  Coins,
  Shield,
  Send,
  Headphones,
  ShieldCheck,
} from "lucide-react";

export interface NavItem {
  href: string;
  label: string;
  icon: React.ComponentType<{ className?: string }>;
  adminOnly?: boolean;
  group?: string;
}

export const navItems: NavItem[] = [
  { href: "/", label: "Pulpit", icon: LayoutDashboard },
  { href: "/orders", label: "Zamówienia", icon: ShoppingCart, group: "Sprzedaż" },
  { href: "/shipments", label: "Przesyłki", icon: Truck, group: "Sprzedaż" },
  { href: "/returns", label: "Zwroty", icon: RotateCcw, group: "Sprzedaż" },
  { href: "/invoices", label: "Faktury", icon: FileText, group: "Sprzedaż" },
  { href: "/orders/import", label: "Import", icon: Upload, group: "Sprzedaż" },
  { href: "/customers", label: "Klienci", icon: Contact, group: "Sprzedaż" },
  { href: "/packing", label: "Pakowanie", icon: ScanBarcode, group: "Sprzedaż" },
  { href: "/reports", label: "Raporty", icon: BarChart3, group: "Sprzedaż" },
  { href: "/products", label: "Produkty", icon: Package, group: "Katalog" },
  { href: "/products/import", label: "Import produktów", icon: Upload, group: "Katalog" },
  { href: "/settings/product-categories", label: "Kategorie", icon: FolderTree, group: "Katalog" },
  { href: "/settings/print-templates", label: "Szablony druku", icon: Printer, group: "Katalog" },
  { href: "/settings/security", label: "Bezpieczeństwo", icon: ShieldCheck, group: "Ogólne" },
  { href: "/settings/company", label: "Firma", icon: Building2, adminOnly: true, group: "Ogólne" },
  { href: "/settings/users", label: "Użytkownicy", icon: Users, adminOnly: true, group: "Ogólne" },
  { href: "/settings/roles", label: "Role", icon: Shield, adminOnly: true, group: "Ogólne" },
  { href: "/settings/order-statuses", label: "Statusy zamówień", icon: ListChecks, adminOnly: true, group: "Sprzedaż - ustawienia" },
  { href: "/settings/custom-fields", label: "Pola niestandardowe", icon: TextCursorInput, adminOnly: true, group: "Sprzedaż - ustawienia" },
  { href: "/settings/price-lists", label: "Cenniki", icon: BadgePercent, adminOnly: true, group: "Sprzedaż - ustawienia" },
  { href: "/settings/invoicing", label: "Fakturowanie", icon: Receipt, adminOnly: true, group: "Sprzedaż - ustawienia" },
  { href: "/settings/ksef", label: "KSeF", icon: FileText, adminOnly: true, group: "Sprzedaż - ustawienia" },
  { href: "/settings/notifications", label: "Powiadomienia", icon: Bell, adminOnly: true, group: "Powiadomienia" },
  { href: "/settings/webhooks", label: "Webhooki", icon: Webhook, adminOnly: true, group: "Powiadomienia" },
  { href: "/settings/inventory", label: "Kontrola magazynowa", icon: ShieldCheck, adminOnly: true, group: "Magazyn" },
  { href: "/settings/warehouses", label: "Magazyny", icon: Warehouse, adminOnly: true, group: "Magazyn" },
  { href: "/settings/warehouse-documents", label: "Dokumenty magazynowe", icon: ClipboardList, adminOnly: true, group: "Magazyn" },
  { href: "/stocktakes", label: "Inwentaryzacja", icon: ClipboardCheck, adminOnly: true, group: "Magazyn" },
  { href: "/integrations", label: "Integracje", icon: Plug, adminOnly: true, group: "Integracje" },
  { href: "/settings/automation", label: "Automatyzacja", icon: Zap, adminOnly: true, group: "Integracje" },
  { href: "/settings/currencies", label: "Waluty", icon: Coins, adminOnly: true, group: "Integracje" },
  { href: "/settings/marketing", label: "Marketing", icon: Send, adminOnly: true, group: "Integracje" },
  { href: "/settings/helpdesk", label: "Helpdesk", icon: Headphones, adminOnly: true, group: "Integracje" },
  { href: "/suppliers", label: "Dostawcy", icon: Factory, adminOnly: true, group: "Integracje" },
  { href: "/settings/sync-jobs", label: "Synchronizacja", icon: RefreshCw, adminOnly: true, group: "Monitoring" },
  { href: "/settings/webhooks/deliveries", label: "Dostawy webhooków", icon: Webhook, adminOnly: true, group: "Monitoring" },
  { href: "/audit", label: "Dziennik aktywności", icon: ScrollText, adminOnly: true, group: "Monitoring" },
];
