-- OPE-405 Provider Registry, Versioning, Lifecycle & Publication
-- All tables are platform-managed (Provider Integration Studio), NOT tenant-scoped
-- and have NO row-level security. They are reached via the OPE-404 platform pool
-- outside any tenant context. The customer-facing read path (private-beta
-- visibility) is a later task and will use a SECURITY DEFINER function.

CREATE TABLE public.provider_definitions (
    id                          uuid PRIMARY KEY DEFAULT public.uuid_generate_v4(),
    provider_key                text NOT NULL UNIQUE,
    display_name                text NOT NULL,
    provider_type               text NOT NULL
        CHECK (provider_type IN ('marketplace', 'carrier', 'supplier', 'shop', 'invoicing', 'edi', 'other')),
    regions                     text[] NOT NULL DEFAULT '{}'::text[],
    business_domains            text[] NOT NULL DEFAULT '{}'::text[],
    owner                       text NOT NULL DEFAULT '',
    source_links                jsonb NOT NULL DEFAULT '[]'::jsonb,
    notes                       text NOT NULL DEFAULT '',
    latest_published_version_id uuid,
    created_at                  timestamptz NOT NULL DEFAULT now(),
    updated_at                  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.provider_versions (
    id                     uuid PRIMARY KEY DEFAULT public.uuid_generate_v4(),
    provider_definition_id uuid NOT NULL REFERENCES public.provider_definitions(id) ON DELETE CASCADE,
    version                text NOT NULL,
    publication_state      text NOT NULL DEFAULT 'research'
        CHECK (publication_state IN ('research', 'designed', 'adapter_in_progress', 'internal_validation',
                                     'private_beta', 'available', 'deprecated', 'retired')),
    changelog              text NOT NULL DEFAULT '',
    compatibility_notes    text NOT NULL DEFAULT '',
    created_by             uuid REFERENCES public.users(id) ON DELETE SET NULL,
    published_by           uuid REFERENCES public.users(id) ON DELETE SET NULL,
    published_at           timestamptz,
    created_at             timestamptz NOT NULL DEFAULT now(),
    updated_at             timestamptz NOT NULL DEFAULT now(),
    UNIQUE (provider_definition_id, version)
);

-- The definition's "currently available" pointer (set when a version reaches
-- 'available'). ON DELETE SET NULL so deleting that version clears the pointer.
ALTER TABLE public.provider_definitions
    ADD CONSTRAINT provider_definitions_latest_version_fkey
    FOREIGN KEY (latest_published_version_id) REFERENCES public.provider_versions(id) ON DELETE SET NULL;

CREATE INDEX idx_provider_versions_definition ON public.provider_versions (provider_definition_id); -- migrate:index-lock-ok

-- Append-only publication audit trail.
CREATE TABLE public.provider_publication_events (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_version_id uuid NOT NULL REFERENCES public.provider_versions(id) ON DELETE CASCADE,
    from_state          text,
    to_state            text NOT NULL,
    action              text NOT NULL DEFAULT 'transition',
    actor_user_id       uuid REFERENCES public.users(id) ON DELETE SET NULL,
    reason              text NOT NULL DEFAULT '',
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_provider_pub_events_version ON public.provider_publication_events (provider_version_id, created_at DESC); -- migrate:index-lock-ok

-- Private-beta tenant allowlist (platform-managed; no RLS).
CREATE TABLE public.provider_tenant_enables (
    id                  uuid PRIMARY KEY DEFAULT public.uuid_generate_v4(),
    provider_version_id uuid NOT NULL REFERENCES public.provider_versions(id) ON DELETE CASCADE,
    tenant_id           uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    enabled_by          uuid REFERENCES public.users(id) ON DELETE SET NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    UNIQUE (provider_version_id, tenant_id)
);
CREATE INDEX idx_provider_tenant_enables_tenant ON public.provider_tenant_enables (tenant_id); -- migrate:index-lock-ok

-- Grant the least-privilege app role(s): production (Supabase) "openoms_app",
-- self-hosted/staging "openoms". Detect dynamically for portability.
DO $$
DECLARE
    app_role text;
    tbl      text;
BEGIN
    FOREACH app_role IN ARRAY ARRAY['openoms_app', 'openoms'] LOOP
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = app_role) THEN
            FOREACH tbl IN ARRAY ARRAY['provider_definitions', 'provider_versions',
                                       'provider_publication_events', 'provider_tenant_enables'] LOOP
                EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO %I', tbl, app_role);
            END LOOP;
            EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO %I', app_role);
        END IF;
    END LOOP;
END;
$$;
