-- OPE-404 Platform-Admin Boundary
-- Platform-admin identity is SEPARATE from tenant RBAC and is NOT tenant-scoped.
-- These tables deliberately have NO row-level security: a platform admin
-- transcends tenants, and the tables are read with the app pool outside any
-- tenant context. No tenant query joins them.

-- ON DELETE RESTRICT (not CASCADE): a platform admin's elevation must not be
-- silently destroyable by a tenant-level user deletion. Demotion is explicit —
-- the platform_admins row must be removed first, then the user may be deleted.
CREATE TABLE public.platform_admins (
    id          uuid PRIMARY KEY DEFAULT public.uuid_generate_v4(),
    user_id     uuid NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE RESTRICT,
    permissions text[] NOT NULL DEFAULT '{}'::text[],
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

-- Dedicated platform-admin audit stream (separate from tenant audit_log).
CREATE TABLE public.platform_audit_log (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
    action        text NOT NULL,
    target_type   text,
    target_id     text,
    metadata      jsonb NOT NULL DEFAULT '{}'::jsonb,
    ip_address    inet,
    created_at    timestamptz NOT NULL DEFAULT now()
);

-- Brand-new empty table in this same migration: the ACCESS EXCLUSIVE lock is
-- harmless (no rows, no concurrent writers), and a CONCURRENTLY index build
-- cannot run inside golang-migrate's transaction. Marked safe per index line.
CREATE INDEX idx_platform_audit_action_created ON public.platform_audit_log (action, created_at DESC); -- migrate:index-lock-ok
CREATE INDEX idx_platform_audit_actor ON public.platform_audit_log (actor_user_id, created_at DESC); -- migrate:index-lock-ok

-- Grant the least-privilege app role(s) access to the new tables. Production
-- (Supabase) uses role "openoms_app"; self-hosted/staging uses "openoms".
-- Detect dynamically so the migration is portable across both.
DO $$
DECLARE
    app_role text;
BEGIN
    FOREACH app_role IN ARRAY ARRAY['openoms_app', 'openoms'] LOOP
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = app_role) THEN
            EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.platform_admins TO %I', app_role);
            EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.platform_audit_log TO %I', app_role);
            EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO %I', app_role);
        END IF;
    END LOOP;
END;
$$;
